### ISSUE TITLE
Docs : 테스트 자동화

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#166]
### 1. 기본적인 테스트 자동화

GitHub Action 을 이용하여 ***트리거*** 기반으로 테스트 자동화를 구현하였습니다.

처음에는 기본적으로 다음과 같이 실행되는 구문을 작성하였습니다.

```cmd
1. npm ci
2. npm run test
```

하지만 해당 구문을 실행하면, `~/test` 디렉토리를 찾지 못하고 있었습니다.
이에,  "package.json"."scripts"."test" 를 다음과 같이 변경하였습니다.

- before : `cross-env NODE_ENV=test jest --findRelatedTests test/ --silent`
- after : `cross-env NODE_ENV=test jest`

아마도 GitHub Action 이 ubuntu 기반의 가상환경에서 돌아가고 있는데, 디렉토리를 찾지 못한 것 같았습니다.
위 구문으로 변경해서 잘 작동을 하고 있지만, ***탐색 범위*** 가 너무 넓어지는 문제가 있습니다.

```yaml
jobs:
  jest_runner:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment and Dependencies, and then Run Jest
        run:  |
          npm ci
          npm test
```

### 2. 테스트가 실패하면 PR 종료

자동화를 도입하는 이유는 ***안정성 및 시간절약*** 의 목적이 가장 크다고 생각합니다.
이에 따라서, 테스트가 실패했을 경우에는 PR 을 종료해야 하는 구문이 있어야 한다고 생각했습니다.

따라서,  PR 을 직접적으로 관여할 수 있는 workflows 를 찾게 되었습니다.

- [GitHub Pull Request가 자동으로 close되는 경우는?](https://engineering.linecorp.com/ko/blog/github-pull-request-auto-close/)
- [GitHub Actions 로 풀리퀘스트 test 검증하기](https://velog.io/@adam2/GitHub-Actions-%EB%A1%9C-%ED%92%80%EB%A6%AC%ED%80%98%EC%8A%A4%ED%8A%B8-test-%EA%B2%80%EC%A6%9D%ED%95%98%EA%B8%B0)

해당 workflows 는 [actions/github-script](https://github.com/actions/github-script) 이며, 일단 돌아가게 만들고 해당 스크립트를 더욱 공부할 생각입니다.

step 1 에서 작성한 스크립트에 다음의 내용을 추가하였습니다.

```yaml
- name: IF Failure and Close PR
  uses: actions/github-script@0.2.0
  with:
    github-token: ${{github.token}}
    script: | 
      const ref = "${{github.ref}}"
      const pull_number = Number(ref.split("/")[2])
      await github.pulls.createReview({
        ...context.repo,
        pull_number,
        body:"테스트 코드 실행 간에 에러가 발생하였습니다.\n테스트 코드를 확인 후 수정해주세요.",
        event: "REQUEST_CHANGES"
      })
      await github.pulls.update({
        ...context.repo,
        pull_number,
        state: "closed"
      }) 
  if: failure()
```

### 3. node_modules 캐싱

현재는 가상환경이 새로 만들어질 때마다, ***의존성 라이브러리*** 를 새로 받고 있습니다.

이러한 부분은 **시간적** 으로도 문제가 되지만, 가장 문제는 **비용** 적인 측면이라고 생각합니다.

기본적으로 GitHub Action 은 pricing 이 꽤나 비싼 서비스고 이에 따라서 ***동일한 파일*** 은 최대한 캐싱을 해야합니다.

_사실, 현업에서 아래 요금이 얼마나 무거운 것인지 정확히 알지는 못합니다. 다만 모든 비용은 최소화할수록 좋다고 생각하며, 이러한 부분에서 가지고 있는 자원을 최소화 할 수 있는 것도 좋은 방법이라고 생각했습니다._

<p align="center"><img src="https://user-images.githubusercontent.com/86306802/190865665-d844056c-0f63-442c-802a-680c9f7f59cf.png"/></p>

이 부분은 github action node_modules cashing 을 통해서 검색하였고 다음을 참고하였습니다.

- [[Github Actions] 사소하지만 중요한 node_modules caching](https://blog.whitekiwi.link/github-actions-cache-node-modules-99935de9e8fa)

```yaml
- name: Cachce node_modules
  uses: actions/cache@v2
  id: node-cache
  env:
    cache-name: cache-node-modules
  with:
    path: node_modules
    key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-node-modules-
- name: Install node_modules
  if: steps.node-cache.outputs.cache-hit != 'true'
  run: npm ci

- name: Run jest
  run: npm test
```

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```
